Class {
	#name : 'ChatPharoToolTestClientStub',
	#superclass : 'Object',
	#category : 'AI-ChatPharo-Tests-Mock',
	#package : 'AI-ChatPharo-Tests',
	#tag : 'Mock'
}

{ #category : 'adding' }
ChatPharoToolTestClientStub >> addPath: segments [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> addPathSegment: aSegment [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> entity: anEntity [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> get [

    ^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> post [

    ^ self

]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> resetEntity [

	^ self
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> response [

    ^ ChatPharoToolTestResponseStub new
]

{ #category : 'adding' }
ChatPharoToolTestClientStub >> timeout: seconds [

    ^ self
]
